import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Header from '../components/Header'
import axios from 'axios'
import SmallCard from '../components/SmallCard'
import MediumCard from '../components/MediumCard'
import LargeCard from '../components/LargeCard'
import Footer from '../components/Footer'
// import styles from '../styles/Home.module.css'

export default function Home({ smallCardData, mediumCardData }) {
  return (
    <div>
      <Head>
        <title>AIRBNB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEADER */}
      <Header />

      {/* BANNER */}
      <Banner />
      {/* main Section */}
      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>
          {/*  small card static Rendering */}
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {smallCardData?.map((item) => (
              <SmallCard key={item.img} img={item.img} distance={item.distance} location={item.location} />
            ))}
          </div>
        </section>
        <section>
          <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>
          {/*  Medium card static Rendering using ES6 */}
          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3 '>
            {mediumCardData?.map(({ title, img }) => (
              <MediumCard key={img} img={img} title={title} />
            ))}
          </div>
        </section>
        <LargeCard
          img='https://links.papareact.com/4cj'
          title='The Greatest Outdoors'
          description='Wish lists curated by Airbnb'
          buttonText='Get Inspired'
        />
      </main>

      {/* FOOTER */}
      <Footer />

    </div>
  )
}


{/*  static Rendering */ }
export async function getStaticProps() {
  const small_card_url = 'https://www.jsonkeeper.com/b/4G1G'
  const smallCardData = await axios.get(small_card_url).then((res) => res.data) //using Axios
  const medium_card_url = 'https://www.jsonkeeper.com/b/VHHT'
  const mediumCardData = await axios.get(medium_card_url).then((res) => res.data)
  // const exploreData = await fetch(url).then((res)=>res.json()) // using fetch

  return {
    props: {
      smallCardData,
      mediumCardData

    }
  }

}